### ISSUE TITLE
Failed to activate the atom-wildfly package

### ISSUE THREAD

**Issue by BenBezac** [bcflynn2/atom-wildfly#1]
Hi, i wanted to try your plugin, and during installing got this :/

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Windows 10
**Thrown From**: [atom-wildfly](https://github.com/Bjond/atom-wildfly) package 0.3.0

### Stack Trace

Failed to activate the atom-wildfly package

```
At E:\workspace\report/build/libs does not exist.

Error: E:\workspace\report/build/libs does not exist.
    at watch (/packages/atom-wildfly/node_modules/node-watch/lib/watch.js:330:7)
    at /packages/atom-wildfly/node_modules/node-watch/lib/watch.js:324:14
    at Array.map (native)
    at watch (/packages/atom-wildfly/node_modules/node-watch/lib/watch.js:323:41)
    at Object.watchFiles (/packages/atom-wildfly/lib/atom-wildfly.js:130:5)
    at Object.activate (/packages/atom-wildfly/lib/atom-wildfly.js:91:10)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:253:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:99:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:642:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/package-manager.js:519:1
    at exit (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/package-manager.js:128:1)
    at triggerExitCallback (~/AppData/Local/atom/app-1.17.2/resources/app/src/buffered-process.js:338:1)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.17.2/resources/app/src/buffered-process.js:368:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -4:06.6.0 snippets:next-tab-stop (input.hidden-input)
     -4:06.6.0 snippets:expand (input.hidden-input)
     -4:06.6.0 editor:indent (input.hidden-input)
     -4:05.6.0 core:save (input.hidden-input)
     -4:04.1.0 core:select-all (input.hidden-input)
     -4:02.0 command-palette:toggle (input.hidden-input)
     -4:00.4.0 core:backspace (input.hidden-input)
     -3:58.8.0 core:confirm (input.hidden-input)
     -3:58.8.0 editor:auto-indent (input.hidden-input)
     -3:54.7.0 core:save (input.hidden-input)
     -2:21.4.0 project-find:show (input.hidden-input)
     -2:19.8.0 core:paste (input.hidden-input)
 22x -2:18.5.0 core:move-left (input.hidden-input)
     -2:16.8.0 core:confirm (input.hidden-input)
     -2:05.2.0 tabs:close-tabs-to-right (div.title)
  7x -1:57.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.22.2 
atom-symfony2 0.2.2 
atom-wildfly 0.3.0 
git-plus 7.9.2 
hyperclick 0.0.40 
hyperlink-hyperclick 1.3.4 
js-hyperclick 1.11.0 
language-javascript-jsx 0.3.7 
language-twig 1.6.3 
navigate 0.1.17 
php-twig 4.0.0 
```
Thx for your answers ;)

**Comment by bcflynn2** [comment]
Hey Ben- sorry, I just saw this issue. I actually think I know what is going on- I have the configuration check for war/ear/jars for deployment in the build/libs folder, which is the maven default, but I don't handle it if it isn't there. I'll add a folder existence check in there to keep that error from popping up.

**Comment by BenBezac** [comment]
Sorry but for now i swap to vscode. Hope it will help some others ppl
